### ISSUE TITLE
Not able to get data when I write someone name in box

### ISSUE THREAD

**Issue by Akshit052** [MZayed47/Signature_ValidatorUI_SSIM#1]
Hello, 
I have got a problem I created dataset in assests folder of different users. But when I run validator the pop-up and when I write someone name in it which i have stored in assests folder then it does not run and shows error and the error is below.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "validator.py", line 45, in submit
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

Can you help me out with it.

**Comment by MZayed47** [comment]
OpenCV is unable to read your images.

Check the following portion around line 45 in validator.py

    for i in range(4):
        file = 'assets/' + name + '/' + name + str(i+1) + '.jpg'
        print("\n\n", file)
        image = cv2.imread(file)
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

make sure your file path is correct. Image names need to contain 1,2,3... at the end for this part to work. Check README/Dataset for this details.

**Comment by Akshit052** [comment]
Thanks, I got it.
